CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "birth_date" date,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "orders" (
  "order_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "payment_status" boolean NOT NULL DEFAULT false,
  "total_amount" decimal(10,2) NOT NULL CHECK (total_amount > 0)
);

CREATE TABLE "tickets" (
  "ticket_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "session_id" integer NOT NULL,
  "seat_id" integer NOT NULL,
  "price" decimal(10,2) NOT NULL CHECK (price > 0),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "seats" (
  "seat_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hall_id" integer NOT NULL,
  "row_number" integer NOT NULL CHECK (row_number > 0),
  "seat_number" integer NOT NULL CHECK (seat_number > 0),
  "zone_type" varchar(30) NOT NULL
);

CREATE TABLE "sessions" (
  "session_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer NOT NULL,
  "hall_id" integer NOT NULL,
  "starts_at" timestamp NOT NULL
);

CREATE TABLE "events" (
  "event_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "short_description" varchar(200),
  "host_name" varchar(100) NOT NULL
);

CREATE TABLE "halls" (
  "hall_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venue_id" integer NOT NULL,
  "hall_number" integer NOT NULL CHECK (hall_number > 0)
);

CREATE TABLE "venues" (
  "venue_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "address" varchar(100) NOT NULL
);

CREATE TABLE "session_price_history" (
  "price_version_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer NOT NULL,
  "price" decimal(10,2) NOT NULL CHECK (price > 0),
  "valid_from" timestamp NOT NULL,
  "valid_to" timestamp,
  "is_current" boolean NOT NULL DEFAULT true,
  CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE UNIQUE INDEX ON "tickets" ("session_id", "seat_id");

CREATE UNIQUE INDEX ON "seats" ("hall_id", "row_number", "seat_number");

CREATE UNIQUE INDEX ON "halls" ("venue_id", "hall_number");

COMMENT ON TABLE "session_price_history" IS 'SCD Type 2: хранит историю изменения цены сеанса';

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("session_id") REFERENCES "sessions" ("session_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("seat_id") REFERENCES "seats" ("seat_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessions" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("event_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessions" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("hall_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seats" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("hall_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "halls" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("venue_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session_price_history" ADD FOREIGN KEY ("session_id") REFERENCES "sessions" ("session_id") DEFERRABLE INITIALLY IMMEDIATE;
